# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4d9e4c67349ea354e3c0febac3bfbb6ea337d5c1312077f9f75fe9aebb6a6b02a3fed3849caba27649e6e7a08cd0d676a6ab6a2572409521c5544c06be1fc9b

test:
  secret_key_base: 8263f087b02e7c409cab4d2821647966d9ddb4f9a033533fdd0c978f2baf78ef301dac8302e72fd5846833cb1842720653616855fa7b5976e7439db15ef91c6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
